# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b156a7b7ff3925e45730a66c5495c48569e848b0c83721f81fce150b8236e9c0d071c4a73c6cc17e96d078337d168ee118d0aafe9e5115810e6634c41ade0f5e

test:
  secret_key_base: 27799b6f80201dbbc3198d723bde8320c62ff8104698b8049964b8f9f21a567d92d5ecf256261a7b48f310d1572d7add5d6d8dfb80074d7ba64a1237898ced4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
