# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f765637e3473b3e5f56bc486f7dc303f19bdf5e235c7ea7c983057ebc3437e16283c12ee584c3b65b0ebd87d19a14c1c89aaf7f0ac939b937f0030fa5dbd8c0b

test:
  secret_key_base: d257c215977f323b7e4c38551971bdda7dd8083522e70261b2356af18600f40440b1eeb0425cf9e9618df5c64358aee599c9989b001d3b26c0ab823c99870599

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
