
[AnswerChoice, Poll, Question, Response, User].map(&:destroy_all)

user1 = User.create(user_name: 'Spencer Chan')
user2 = User.create(user_name: 'Andrew Booth')
user3 = User.create(user_name: 'Dragon Slayer')
user4 = User.create(user_name: 'NiteWeaver')
user5 = User.create(user_name: 'robomonkey10')

poll1 = Poll.create(title: 'What did you have for lunch today?', user_id: user1.id)
poll2 = Poll.create(title: 'What\'s our next question?', user_id: user2.id)
poll3 = Poll.create(title: 'Your favorite language', user_id: user5.id)

question1 = Question.create(poll_id: poll1.id, body: 'Did you eat chicken?')
question2 = Question.create(poll_id: poll1.id, body: 'Did you drink water?')
question3 = Question.create(poll_id: poll1.id, body: 'What did you have for dessert?')
question4 = Question.create(poll_id: poll2.id, body: 'Who the hell knows?')
question5 = Question.create(poll_id: poll2.id, body: 'Who cares, do you?')
question6 = Question.create(poll_id: poll3.id, body: 'What language do you speak?')
question7 = Question.create(poll_id: poll3.id, body: 'What is your favorite langugae?')

answer1 = AnswerChoice.create(question_id: question1.id, body: 'Yes')
answer2 = AnswerChoice.create(question_id: question1.id, body: 'No')
answer3 = AnswerChoice.create(question_id: question2.id, body: 'Yes')
answer4 = AnswerChoice.create(question_id: question2.id, body: 'No')
answer5 = AnswerChoice.create(question_id: question3.id, body: 'Ice Cream')
answer6 = AnswerChoice.create(question_id: question3.id, body: 'Beef')
answer7 = AnswerChoice.create(question_id: question3.id, body: 'Cookie')
answer8 = AnswerChoice.create(question_id: question4.id, body: 'Kelly???')
answer9 = AnswerChoice.create(question_id: question4.id, body: 'Aaron :)')
answer10 = AnswerChoice.create(question_id: question4.id, body: 'Dallas :D')
answer12 = AnswerChoice.create(question_id: question5.id, body: 'Yes')
answer13 = AnswerChoice.create(question_id: question5.id, body: 'No')
answer14 = AnswerChoice.create(question_id: question6.id, body: 'English')
answer15 = AnswerChoice.create(question_id: question6.id, body: 'Other')
answer16 = AnswerChoice.create(question_id: question7.id, body: 'English')
answer17 = AnswerChoice.create(question_id: question7.id, body: 'Other')

Response.create(user_id: user4.id, answer_choice_id: answer6.id)
Response.create(user_id: user4.id, answer_choice_id: answer1.id)
Response.create(user_id: user4.id, answer_choice_id: answer3.id)
Response.create(user_id: user2.id, answer_choice_id: answer5.id)
Response.create(user_id: user2.id, answer_choice_id: answer2.id)
Response.create(user_id: user2.id, answer_choice_id: answer4.id)

Response.create(user_id: user1.id, answer_choice_id: answer8.id)
